name: Lint

on:
  push:

env:
  TERRAFORM_VERSION: "1.3.9"
  TFSEC_VERSION: "v1.28.1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform format
        run: terraform fmt -recursive -check

      - name: Run tfsec linter
        id: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          version: ${{ env.TFSEC_VERSION }}
