name: Lint

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    name: Linting

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install dependencies in .tool-versions
        uses: asdf-vm/actions/install@v2

      - name: Run Terraform format
        run: terraform fmt -recursive -check

      - name: Run trivy linter
        run: trivy config .
