const INFRA_CORE_PATH = 'core/';
const INFRA_CORE_MAIN_PATH = `${INFRA_CORE_PATH}/main.tf`;
const INFRA_CORE_OUTPUTS_PATH = `${INFRA_CORE_PATH}/outputs.tf`;
const INFRA_CORE_VARIABLES_PATH = `${INFRA_CORE_PATH}/variables.tf`;
const INFRA_CORE_LOCALS_PATH = `${INFRA_CORE_PATH}/locals.tf`;
const INFRA_CORE_DATA_PATH = `${INFRA_CORE_PATH}/data.tf`;

const INFRA_SHARED_PATH = 'shared';
const INFRA_SHARED_MAIN_PATH = `${INFRA_SHARED_PATH}/main.tf`;
const INFRA_SHARED_OUTPUTS_PATH = `${INFRA_SHARED_PATH}/outputs.tf`;
const INFRA_SHARED_VARIABLES_PATH = `${INFRA_SHARED_PATH}/variables.tf`;
const INFRA_SHARED_LOCALS_PATH = `${INFRA_SHARED_PATH}/locals.tf`;
const INFRA_SHARED_DATA_PATH = `${INFRA_SHARED_PATH}/data.tf`;

export {
  INFRA_CORE_PATH,
  INFRA_CORE_MAIN_PATH,
  INFRA_CORE_OUTPUTS_PATH,
  INFRA_CORE_VARIABLES_PATH,
  INFRA_CORE_LOCALS_PATH,
  INFRA_CORE_DATA_PATH,
  INFRA_SHARED_PATH,
  INFRA_SHARED_MAIN_PATH,
  INFRA_SHARED_OUTPUTS_PATH,
  INFRA_SHARED_VARIABLES_PATH,
  INFRA_SHARED_LOCALS_PATH,
  INFRA_SHARED_DATA_PATH,
};
