const INFRA_BASE_PATH = 'base';
const INFRA_BASE_MAIN_PATH = `${INFRA_BASE_PATH}/main.tf`;
const INFRA_BASE_OUTPUTS_PATH = `${INFRA_BASE_PATH}/outputs.tf`;
const INFRA_BASE_VARIABLES_PATH = `${INFRA_BASE_PATH}/variables.tf`;

const INFRA_SHARED_PATH = 'shared';
const INFRA_SHARED_MAIN_PATH = `${INFRA_SHARED_PATH}/main.tf`;
const INFRA_SHARED_OUTPUTS_PATH = `${INFRA_SHARED_PATH}/outputs.tf`;
const INFRA_SHARED_VARIABLES_PATH = `${INFRA_SHARED_PATH}/variables.tf`;
export {
  INFRA_BASE_PATH,
  INFRA_BASE_MAIN_PATH,
  INFRA_BASE_OUTPUTS_PATH,
  INFRA_BASE_VARIABLES_PATH,
  INFRA_SHARED_PATH,
  INFRA_SHARED_MAIN_PATH,
  INFRA_SHARED_OUTPUTS_PATH,
  INFRA_SHARED_VARIABLES_PATH,
};
