const INFRA_BASE_PATH = 'base';
const INFRA_BASE_MAIN_PATH = `${INFRA_BASE_PATH}/main.tf`;
const INFRA_BASE_OUTPUTS_PATH = `${INFRA_BASE_PATH}/outputs.tf`;
const INFRA_BASE_VARIABLES_PATH = `${INFRA_BASE_PATH}/variables.tf`;

const INFRA_SHARED_PATH = 'shared';
const INFRA_SHARED_MAIN_PATH = `${INFRA_SHARED_PATH}/main.tf`;
const INFRA_SHARED_OUTPUTS_PATH = `${INFRA_SHARED_PATH}/outputs.tf`;
const INFRA_SHARED_VARIABLES_PATH = `${INFRA_SHARED_PATH}/variables.tf`;

const AWS_SECURITY_GROUP_PATH = `modules/security_group`;
const AWS_SECURITY_GROUP_MAIN_PATH = `${AWS_SECURITY_GROUP_PATH}/main.tf`;
const AWS_SECURITY_GROUP_OUTPUTS_PATH = `${AWS_SECURITY_GROUP_PATH}/outputs.tf`;
const AWS_SECURITY_GROUP_VARIABLES_PATH = `${AWS_SECURITY_GROUP_PATH}/variables.tf`;

export {
  INFRA_BASE_PATH,
  INFRA_BASE_MAIN_PATH,
  INFRA_BASE_OUTPUTS_PATH,
  INFRA_BASE_VARIABLES_PATH,
  INFRA_SHARED_PATH,
  INFRA_SHARED_MAIN_PATH,
  INFRA_SHARED_OUTPUTS_PATH,
  INFRA_SHARED_VARIABLES_PATH,
  AWS_SECURITY_GROUP_PATH,
  AWS_SECURITY_GROUP_MAIN_PATH,
  AWS_SECURITY_GROUP_OUTPUTS_PATH,
  AWS_SECURITY_GROUP_VARIABLES_PATH,
};
