name: Publish Github Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - develop
      - feature/20-create-project-wiki
  workflow_dispatch:

jobs:
  publish:
    name: Publish Github Wiki

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Publish Github Wiki
        uses: nimblehq/publish-github-wiki-action@v1.0
        with:
          user_name: nimble-wiki-bot
          user_email: dev@nimblehq.co
          user_access_token: ${{ secrets.GH_BOT_PAT }}
