name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node npm
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-infrastructure-templates-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-infrastructure-templates-

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test
