name: Test Generated Project

on:
  pull_request:
    types: [opened, synchronize]

env:
  TERRAFORM_VERSION: "1.5.5"

jobs:
  test:
    name: Run Tests Generated Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Cache Node npm
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-infrastructure-templates-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-infrastructure-templates

      - name: Install modules
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Generate project
        run: . ./scripts/generateAdvancedAWS.sh

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform format
        run: terraform fmt -recursive -check

      - name: Run trivy linter
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: '.'
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
